name: API Docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi
      - name: Run FastAPI
        run: |
          nohup poetry run uvicorn esg_lex_harmonizer.api.advanced_api:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000/docs; then
              echo "API 啟動成功"
              break
            fi
            echo "等待 API 啟動中 ($i/30)..."
            sleep 2
          done
      - name: Generate API Docs
        run: poetry run python scripts/generate_api_docs.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
      - name: Upload uvicorn log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: uvicorn-log
          path: uvicorn.log 